const data = [
  {
    id: 1,
    name: "SOPA CRIOLLA",
    description: "Descripcion SOPA CRIOLLA",
    price: 8,
    urlPhoto: "/img/menus/1_sopa-criolla.jpg",
    state: "1",
    categoryMenu: {
      id: 1,
      name: "SOPAS",
      description: "Mi Descripcion SOPAS",
    },
  },
  {
    id: 2,
    name: "SOPA DE POLLO",
    description: "Descripcion SOPA DE POLLO",
    price: 8,
    urlPhoto: "/img/menus/1_sopa-de-pollo.jpg",
    state: "1",
    categoryMenu: {
      id: 1,
      name: "SOPAS",
      description: "Mi Descripcion SOPAS",
    },
  },
  {
    id: 3,
    name: "SOPA DE CARNE",
    description: "Descripcion SOPA DE CARNE",
    price: 8,
    urlPhoto: "/img/menus/1_sopa-de-carne.jpg",
    state: "1",
    categoryMenu: {
      id: 1,
      name: "SOPAS",
      description: "Mi Descripcion SOPAS",
    },
  },
  {
    id: 4,
    name: "SOPA A LA MINUTA",
    description: "Descripcion SOPA A LA MINUTA",
    price: 8,
    urlPhoto: "/img/menus/1_sopa-a-la-minuta.jpg",
    state: "1",
    categoryMenu: {
      id: 1,
      name: "SOPAS",
      description: "Mi Descripcion SOPAS",
    },
  },
  {
    id: 5,
    name: "MENESTRON",
    description: "Descripcion MENESTRON",
    price: 8,
    urlPhoto: "/img/menus/1_menestron.jpg",
    state: "1",
    categoryMenu: {
      id: 1,
      name: "SOPAS",
      description: "Mi Descripcion SOPAS",
    },
  },
  {
    id: 6,
    name: "TEQUEÑOS",
    description: "Descripcion TEQUEÑOS",
    price: 5,
    urlPhoto: "/img/menus/2_tequeños.jpg",
    state: "1",
    categoryMenu: {
      id: 2,
      name: "ENTRADAS",
      description: "Mi Descripcion ENTRADAS",
    },
  },
  {
    id: 7,
    name: "PAPA A LA HUANCAINA",
    description: "Descripcion PAPA A LA HUANCAINA",
    price: 5,
    urlPhoto: "/img/menus/2_papa-a-la-huancaina.jpg",
    state: "1",
    categoryMenu: {
      id: 2,
      name: "ENTRADAS",
      description: "Mi Descripcion ENTRADAS",
    },
  },
  {
    id: 8,
    name: "PALTA RELLENA",
    description: "Descripcion PALTA RELLENA",
    price: 5,
    urlPhoto: "/img/menus/2_palta-rellena.jpg",
    state: "1",
    categoryMenu: {
      id: 2,
      name: "ENTRADAS",
      description: "Mi Descripcion ENTRADAS",
    },
  },
  {
    id: 9,
    name: "CAUSA RELLENA",
    description: "Descripcion CAUSA RELLENA",
    price: 5,
    urlPhoto: "/img/menus/2_causa-rellena.jpg",
    state: "1",
    categoryMenu: {
      id: 2,
      name: "ENTRADAS",
      description: "Mi Descripcion ENTRADAS",
    },
  },
  {
    id: 10,
    name: "PAPA RELLENA",
    description: "Descripcion PAPA RELLENA",
    price: 5,
    urlPhoto: "/img/menus/2_papa-rellena.jpg",
    state: "1",
    categoryMenu: {
      id: 2,
      name: "ENTRADAS",
      description: "Mi Descripcion ENTRADAS",
    },
  },
  {
    id: 11,
    name: "TAMAL",
    description: "Descripcion TAMAL",
    price: 5,
    urlPhoto: "/img/menus/2_tamal.jpg",
    state: "1",
    categoryMenu: {
      id: 2,
      name: "ENTRADAS",
      description: "Mi Descripcion ENTRADAS",
    },
  },
  {
    id: 12,
    name: "LOMO SALTADO",
    description: "Descripcion LOMO SALTADO",
    price: 20,
    urlPhoto: "/img/menus/3_lomo-saltado.jpg",
    state: "1",
    categoryMenu: {
      id: 3,
      name: "PLATO PRINCIPAL",
      description: "Mi Descripcion PLATO PRINCIPAL",
    },
  },
  {
    id: 13,
    name: "SOPA SECA",
    description: "Descripcion SOPA SECA",
    price: 20,
    urlPhoto: "/img/menus/3_sopa-seca.jpg",
    state: "1",
    categoryMenu: {
      id: 3,
      name: "PLATO PRINCIPAL",
      description: "Mi Descripcion PLATO PRINCIPAL",
    },
  },
  {
    id: 14,
    name: "CHANCHO A LA CAJA CHINA",
    description: "Descripcion CHANCHO A LA CAJA CHINA",
    price: 20,
    urlPhoto: "/img/menus/3_chancho-a-la-caja-china.jpg",
    state: "1",
    categoryMenu: {
      id: 3,
      name: "PLATO PRINCIPAL",
      description: "Mi Descripcion PLATO PRINCIPAL",
    },
  },
  {
    id: 15,
    name: "ARROZ CON POLLO",
    description: "Descripcion ARROZ CON POLLO",
    price: 20,
    urlPhoto: "/img/menus/3_arroz-con-pollo.jpg",
    state: "1",
    categoryMenu: {
      id: 3,
      name: "PLATO PRINCIPAL",
      description: "Mi Descripcion PLATO PRINCIPAL",
    },
  },
  {
    id: 16,
    name: "AJI DE GALLINA",
    description: "Descripcion AJI DE GALLINA",
    price: 20,
    urlPhoto: "/img/menus/3_aji-de-gallina.jpg",
    state: "1",
    categoryMenu: {
      id: 3,
      name: "PLATO PRINCIPAL",
      description: "Mi Descripcion PLATO PRINCIPAL",
    },
  },
  {
    id: 17,
    name: "ESCABECHE DE POLLO",
    description: "Descripcion ESCABECHE DE POLLO",
    price: 20,
    urlPhoto: "/img/menus/3_escabeche-de-pollo.jpg",
    state: "1",
    categoryMenu: {
      id: 3,
      name: "PLATO PRINCIPAL",
      description: "Mi Descripcion PLATO PRINCIPAL",
    },
  },
  {
    id: 18,
    name: "PICARONES",
    description: "Descripcion PICARONES",
    price: 10,
    urlPhoto: "/img/menus/5_picarones.jpg",
    state: "1",
    categoryMenu: {
      id: 5,
      name: "POSTRES",
      description: "Mi Descripcion POSTRES",
    },
  },
  {
    id: 19,
    name: "LECHE ASADA",
    description: "Descripcion LECHE ASADA",
    price: 10,
    urlPhoto: "/img/menus/5_leche-asada.jpg",
    state: "1",
    categoryMenu: {
      id: 5,
      name: "POSTRES",
      description: "Mi Descripcion POSTRES",
    },
  },
  {
    id: 20,
    name: "PIE DE LIMON",
    description: "Descripcion PIE DE LIMON",
    price: 10,
    urlPhoto: "/img/menus/5_pie-de-limon.jpg",
    state: "1",
    categoryMenu: {
      id: 5,
      name: "POSTRES",
      description: "Mi Descripcion POSTRES",
    },
  },
  {
    id: 21,
    name: "ALFAJORES",
    description: "Descripcion ALFAJORES",
    price: 10,
    urlPhoto: "/img/menus/5_alfajores.jpg",
    state: "1",
    categoryMenu: {
      id: 5,
      name: "POSTRES",
      description: "Mi Descripcion POSTRES",
    },
  },
  {
    id: 22,
    name: "ARROZ CON LECHE",
    description: "Descripcion ARROZ CON LECHE",
    price: 10,
    urlPhoto: "/img/menus/5_arroz-con-leche.jpg",
    state: "1",
    categoryMenu: {
      id: 5,
      name: "POSTRES",
      description: "Mi Descripcion POSTRES",
    },
  },
  {
    id: 23,
    name: "GASEOSA 3L",
    description: "Descripcion GASEOSA 3L",
    price: 13,
    urlPhoto: "/img/menus/7_gaseosa_3l.jpg",
    state: "1",
    categoryMenu: {
      id: 7,
      name: "BEBIDAS",
      description: "Mi Descripcion BEBIDAS",
    },
  },
  {
    id: 24,
    name: "GASEOSA 2L",
    description: "Descripcion GASEOSA 2L",
    price: 9,
    urlPhoto: "/img/menus/7_gaseosa_2l.jpg",
    state: "1",
    categoryMenu: {
      id: 7,
      name: "BEBIDAS",
      description: "Mi Descripcion BEBIDAS",
    },
  },
  {
    id: 25,
    name: "GASEOSA PERSONAL",
    description: "Descripcion PERSONAL",
    price: 5,
    urlPhoto: "/img/menus/7_gaseosa_personal.jpg",
    state: "1",
    categoryMenu: {
      id: 7,
      name: "BEBIDAS",
      description: "Mi Descripcion BEBIDAS",
    },
  },
];
export default data;